use customer_behaviour
select * from customer
alter table customer alter column purchase_amount float
---Total revenue generated by male vs female customers----
select gender, sum(purchase_amount) as Total_revenue
from customer
group by gender

--which customers used a discount but still spent more than average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>(select avg(purchase_amount) from customer)


---which are the top 5 products with the highest average review rating---

select top 5 item_purchased, round(avg(review_rating),3) as avg_rating
from customer
group by item_purchased
order by avg_rating desc

--compare the average purchase amount between standard and express shipping

select shipping_type, round(avg(purchase_amount),2) as avg_purchase_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
select subscription_status, 
count(customer_id) as total_customers,
sum(purchase_amount) as Total_revenue,
round(avg(purchase_amount),2) as Average_apend
from customer
group by subscription_status



---segment customers into new returning and loyal based on their total 
--number of previous purchases & show the count of each segment---
---1--new, 2 and 10--returning , >10 ---loyal
with cte3 as (
select customer_id, previous_purchases,
(case when previous_purchases=1 then 'new' 
when previous_purchases between 2 and 10 then 'returning'
when previous_purchases>10 then 'loyal' end) as customer_segmentation
from customer)
select customer_segmentation,
count(*) as segment_count
from cte3
group by customer_segmentation

---top 3 most purchased products within each category--
with cte4 as (
select category,item_purchased ,
count(item_purchased) as purchase_count,
ROW_NUMBER() over (partition by category order by count(item_purchased) desc) as rn
from customer
group by category,item_purchased)
select category, item_purchased, purchase_count
from cte4
where rn between 1 and 3

--are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as customer_count,
cast(count(customer_id)*100 / (select count(customer_id) from customer where previous_purchases>5) as decimal(10,2)) as sub_per
from customer
where previous_purchases>5
group by subscription_status

---revenue contribution of each age group---
select age_group,
sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc




































